baseurl = "/"
languageCode = "en-us"
title = "This Week in R Learning (#twirl)"
theme = "hyde-fork"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Me"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/francisbarton/twirl.rbind.io"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ludictech"

[params]
    description = "A learning blog"
    
    # font = "Mina"
    # font = "Noto Serif"
    font = "Merriweather"
    
    # accent = "#0076a3" # "allports"
    # accent = "#5c5d75" # "comet"
    accent = "#354e8c" # "chambray"
    
    layoutReverse = true
    themeColor = "theme-base-0e"
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    # highlightjsTheme = "github"
    # highlightjsTheme = "gruvbox-dark"
    highlightjsTheme = "atom-one-dark"
    # highlightjsTheme = "tomorrow-night-eighties"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "site logo"
