baseurl = "https://twirl-rbind.netlify.app/"
languageCode = "en-gb"
title = "#twirl"
theme = "hyde-fork"
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
ignoreFiles = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']

[permalinks]
    post = "/:slug/"

[author]
    image = "images/twirl_hex_v2.png"
    alt = "twirl hex logo"


# main menu Items
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

# social/contact menu

[[menu.contact]]
    name = "GitHub"
    url = "https://github.com/francisbarton/"
    icon = "github"
    weight = 1

[[menu.contact]]
    name = "Twitter"
    url = "https://twitter.com/ludictech"
    icon = "twitter"
    weight = 2

# General site parameters
[params]
    author = "Francis Barton"
    subtitle = "Less-than-weekly learning notes"
    description = "(This Week in R Learning)"

    disable_mathjax = true
    
    contactHeader = false

    # twitterImage = ""
    
    copyright = "CC0 1.0 Universal Licence"
    footer = false
    
    # number of recent posts to display on front page
    n_posts_front = 10
    
    layoutReverse = true
    themeColor = "theme-base-0e"

    # accent = "#0076a3" # "allports"
    # accent = "#5c5d75" # "comet"
    accent = "#354e8c" # "chambray"
    
    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = ["css/hyde_tweaks.css"]
    
    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    # customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    
    # highlightjsTheme = "ocean"
    # highlightjsTheme = "zenburn"
    # highlightjsTheme = "hybrid"
    # highlightjsTheme = "agate"
    # highlightjsTheme = "gruvbox-dark"
    highlightjsTheme = "atom-one-dark"
    # highlightjsTheme = "tomorrow-night-eighties"

    # MathJaxCDN = "//cdn.bootcss.com"
    # MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

# also needs to live in "static"
[params.logo]
    url = "images/twirl_hex_v2.png"
    width = 50
    height = 50
    alt = "twirl hex logo"

# for hugodown
# [markup]
#   defaultMarkdownHandler = "goldmark"
#   [markup.goldmark.renderer]
#     unsafe = true