sticker("static/images/twirl_logo_500x400_v5.png",
        package = "twirl",
        p_size = 32,
        p_color = "white",
        p_family = "Sedgwick Ave",
        p_x = 0.6,
        p_y = 0.8,
        s_x = 1,
        s_y = 1,
        s_width = .75,
        s_height = .6,
        h_fill = "#435763",
        h_color = "#aaaf6e",
        spotlight = TRUE,
        l_x = 0.6,
        l_y = 1,
        white_around_sticker = FALSE,
        filename="static/images/twirl_hex_v2.png")

